### ISSUE TITLE
Provide a single json configuration file for srcheck

### ISSUE THREAD

**Issue by andrealbinop** [sglebs/srccheck#64]
@sglebs ,

All srccheck utilities uses command line arguments mixed with json files for metrics threshold. When using them in pipelines (GitLab CI, Travis CI, etc), repositories need multiple configuration files and scripts to setup srccheck. Usually a project will need:

- 4 json files for max metrics (project, file, class, routines)
- 1 or more json files for scatterplot reports
- und script files to generate udb
- multiple script files to run srccheck and related utilities.

To alleviate that,  inspired by [eslint](https://eslint.org/docs/user-guide/configuring), I propose a single json named `.srccheck.json` that allows configuring:

- All max metrics (project, file, class, routines)
- understand related configuration (database path, dllDir, etc)
- scatterplot json configuration. Since project could use multiple scatterplot reports, we would need to bind an id to scatterplots configuration and adapt command line utility to reference it. Something like: `srcscatterplot --config=project_stability` (check sample json below).

Below a sample of this json configuration file:

```json
{
  "db": "/Users/mqm/Downloads/django.udb",
  "dllDir": "/Applications/Understand.app/Contents/MacOS/Python",
  "maxPrjMetrics": {
    "AvgCyclomaticModified": 2,
    "MaxNesting": 4,
    "MaxCyclomaticModified": 10
  },
  "maxFileMetrics": {
    "CountLineCode": 500,
    "CountDeclFunction": 30,
    "CountDeclClass": 25,
    "MEDIAN:CountDeclClass": 2
  },
  "maxClassMetrics": {
    "CountDeclMethod": 20,
    "MaxInheritanceTree": 4,
    "CountClassCoupled": 20,
    "PercentLackOfCohesion": 50
  },
  "maxRoutineMetrics": {
    "CountLineCode": 80,
    "MEDIAN:CountLineCode": 80,
    "STDEV:CountLineCode": 80,
    "CountParams": 12,
    "AVG:CountParams": 3,
    "CyclomaticModified": 7,
    "MEDIAN:CyclomaticModified": 7,
    "STDEV:CyclomaticModified": 7
  },
  "scatterplots": {
    "project_stability": {
      "File": [
        {
          "xMetric": "CountLineCode",
          "yMetric": "MaxCyclomaticModified",
          "ballMetric": "MaxNesting",
          "xMetricMinValue": 100,
          "yMetricMinValue": 10,
          "ballMetricMinValue": 0
        }
      ],
      "Class": [
        {
          "xMetric": "CountLineCode",
          "yMetric": "CountClassCoupled",
          "ballMetric": "PercentLackOfCohesion",
          "xMetricMinValue": 100,
          "yMetricMinValue": 10,
          "ballMetricMinValue": 0
        }
      ],
      "Routine": [
        {
          "xMetric": "CountLineCode",
          "yMetric": "CyclomaticModified",
          "ballMetric": "MaxNesting",
          "xMetricMinValue": 10,
          "yMetricMinValue": 5,
          "ballMetricMinValue": 1
        }
      ]
    }
  }
}
```

@sglebs , if you authorize this proposal I'll PR the changes as soon as I can. I intend to keep srcheck compatible with previous configuration models.

**Comment by sglebs** [comment]
@andreptb your problems are already addressed by https://github.com/sglebs/srccheck/issues/61 . Simply use a URL to the json file(s) to share them across projects.

**Comment by andrealbinop** [comment]
@sglebs ,

I don't see what URL to load json files have to do with my request. Locally or remotelly, my proposal addresses better organization for srccheck configuration files, just like projects such as [eslint](https://eslint.org/docs/user-guide/configuring), [findbugs](https://github.com/findbugsproject/findbugs/blob/master/findbugs/etc/findbugs.xml), [pep8](http://pep8.readthedocs.io/en/release-1.7.x/intro.html) and many others.

Additionally, this configuration file also could hold understand config entries, maybe even supporting creating udb file on demand. For example:

```json
{
  "db": "/Users/mqm/Downloads/django.udb",
  "dllDir": "/Applications/Understand.app/Contents/MacOS/Python",
  "folders": ["./app"],
  "languages": ["python"],
  "exclude": ["*tests*","*Test*","mock*","Mock*"],
  ...
}
```

**Comment by sglebs** [comment]
@andreptb the URL support goes against your complaint of having to duplicate files for each git repo. If the files have the same parameters, just have them in another repo and URL-share them. You will get rid of your duplication problem.

I dislike the idea of srccheck creating the UDB file. It brings complexity into srccheck. To me, it violates the KISS principle. Use many tools and combine them, just like Unix did.

Using a single monolythic file also prevents me from running from the cmd-line with no files. It can all be made explicit in your invocation line, in a shell script. Easy to carry around.

Combining many files can be solved easily with a simple OS mechanism: a folder. No need to put it all in a single gigantic file. Aggregation can be acomplished this way.

Anyway, I believe it boils down to personal taste. But I will give it more thought though.

**Comment by andrealbinop** [comment]
@sglebs 

You convinced me that's a personal taste. In Javascript world, specially for web applications, the staggering amount of configuration files makes it really hard to keep track of each one. Take a look at [JedWatson/react-select](https://github.com/JedWatson/react-select), just a simple select2 component with at least 20 configuration files.

I could find a few discussions on the Internet of people sharing my point of view:

- [Kilian Foth](https://softwareengineering.stackexchange.com/questions/287308/should-one-use-many-small-configuration-files-for-script-or-a-single-large-confi#comment592986_287310) mentioned: "Using one file for each value is essentially abusing the file system as a data base. Don't do that. Both files systems and databases are good at what they do, and not so good at doing the other's job."
- [Death by thousand config files](https://gabri.me/blog/death-by-thousand-config-files/)
