### ISSUE TITLE
OO Instability and Abstractness Plots

### ISSUE THREAD

**Issue by tanquetav** [sglebs/srccheck#72]
I am analyzing  a python project and srccheck is not detecting abstractness in my project. 

Understand detects the class abstract, from ABC, and methods are annotated   as abstractmethods, 
![evidencia_01](https://user-images.githubusercontent.com/4633755/45302487-d6dd3100-b4e9-11e8-9685-f447a74736dc.png)

However the instability.csv generated from project complains about zero abstractness
![evidencia_02](https://user-images.githubusercontent.com/4633755/45302495-dba1e500-b4e9-11e8-8f99-4b285ca49373.png)

**Comment by sglebs** [comment]
It looks like not all of your packages are really packages for Understand:

   * [Node (Package): repositories.atividade (yatividade@E1B6740F777062F2A),
   * Node (Package): tests.base (ybase@Etests.base), 
   * Node (Package): tests.cases (ycases@Etests.cases), 
   * Node (Package): commons (ycommons@Ecommons), 
   * Node (Package): configurations (yconfigurations@Econfigurations), 
   * Node (Package): controllers (ycontrollers@Econtrollers), 
   * Node (Package): repositories.etiquetas (yetiquetas@ECD7B1602AF63E957), 
   * Node (Package): json (yjson@Ejson), 
   * Node (Package): models (ymodels@Emodels), 
   * Node (Package): repositories (yrepositories@Erepositories), 
   * Node (Package): requests (yrequests@Erequests), 
   * Node (Package): tests.sdk (ysdk@Etests.sdk), 
   * Node (Package): services (yservices@Eservices), 
   * Node (Package): repositories.tarefa (ytarefa@E1938BBE7621A57C3), 
   * Node (Package): tests (ytests@Etests)]

I believe Understand only tags as a package when a __init__.py is found inside (classic Python way) and you don't have these in your inner directories. This may be a bug in Understand with newer versions of Python (3.3 and above).

**Comment by sglebs** [comment]
When an __init__.py is added to the API sub-dir, Understand then returns repositories.API in the list of packages, and instability.csv output by genInstability does indicate Abstractness=1.

**Comment by sglebs** [comment]
Can I close this, @tanquetav ?
