### ISSUE TITLE
Srccheck CountParams metric error counting

### ISSUE THREAD

**Issue by paulorbpacheco** [sglebs/srccheck#74]
I think that there is an issue when srccheck is counting how many parameters there are in a routine.

Actually I'm having this building break issue:  
![scrcheck1](https://user-images.githubusercontent.com/4061153/46100551-0a81b180-c1a0-11e8-965f-b0b4f721e559.png)
  
But if you look the source code:  
![scrcheck2](https://user-images.githubusercontent.com/4061153/46100857-d8bd1a80-c1a0-11e8-8bbe-86e75991864c.png)
As you can see, I have 5 parameters, not 6.  
  
So, take a look at index.html, the exported file from Understand with all project information:  
![scrcheck3](https://user-images.githubusercontent.com/4061153/46101218-bf689e00-c1a1-11e8-98de-a28ab6afe09a.png)

We're able to realize that Understand identifies the lambda's param, but the scrcheck  dont. So I don't know if this is an Undertsand's error or srccheck. Can you help me @sglebs ?

Thanks in advance.

Regards,

Paulo

**Comment by sglebs** [comment]
Hmmm I think that "Catch Parameter" is being returned. In other words, I probably have to ask for "Parameter, except the Catch ones". Currently I do this:

metric_dict ["CountParams"] = len(entity.ents("Define", "Parameter"))

So I suspect that "Catch Parameter" is also returned. I wil double check with their support.

**Comment by sglebs** [comment]
I am guessing the fix is to change it to:

metric_dict ["CountParams"] = len(entity.ents("Define", "Parameter ~Catch"))

**Comment by sglebs** [comment]
De: SciTools Support <support@scitools.com> 
Enviada em: terça-feira, 8 de janeiro de 2019 16:33
Para: Marcio Marchini <marcio.marchini@softplan.com.br>
Cc: Paulo Roberto Blaschke Pacheco <paulo.pacheco@softplan.com.br>; Romulo Augusto Campos Pelachini <romulo@softplan.com.br>; Andre Justi <andre.justi@softplan.com.br>; Luiz Guilherme Bauer Fraga Moreira <luiz.moreira@softplan.com.br>
Assunto: Re: CountParams, filter Catch Parameter out?

Hi Marcio,

It looks correct to me. “Parameter ~Catch” should be all that’s needed.

Regards.
Kyle Jackson
