### ISSUE TITLE
xmlkaloi commandline is not recognized

### ISSUE THREAD

**Issue by hramos8** [sglebs/srccheck#86]
The version 0.2.7 introduced xmlkaloi feature. But after paver installation, the comand "xmlkaloi" is not recognized

**Comment by sglebs** [comment]
Please try 0.2.8

**Comment by sglebs** [comment]
Sorry, I had already fixed it as soon as you entered the issue: https://github.com/sglebs/srccheck/commit/736cd88b890aac3663d0b655cda551ab65df151d

Please try 0.2.8

**Comment by hramos8** [comment]
It's working!
